/**
 * 운영 안정화 E2E — 실수해도 데이터가 사라지지 않는가, 운영 OS 와 같은 진실인가, 끊겨도 미팅 내용이 남는가.
 * local 모드(localStorage)에서 Supabase RPC 와 같은 규칙을 검증한다(Local Repository Parity).
 */
import { expect, test } from '@playwright/test'
import { SHOTS, answerAll, prepareCompany } from './helpers'

async function loginPartner(page: import('@playwright/test').Page) {
  await page.goto('/login')
  await page.getByTestId('login-partner').click()
  await expect(page).toHaveURL(/\/$/)
}
async function switchRole(page: import('@playwright/test').Page, to: '마스터로 전환' | '파트너로 전환') {
  await page.goto('/settings')
  await page.getByRole('button', { name: to }).click()
}

test.describe('운영 안정화', () => {
  test('고객 lifecycle — 보관 → 목록에서 사라짐 → 휴지통 → 복구 → 보관 → 영구삭제(2단계·회사명 입력)', async ({ page }, testInfo) => {
    const tag = testInfo.project.name
    await loginPartner(page)
    await prepareCompany(page, '삭제테스트상사')
    // 상세에서 휴지통으로 이동 (1차 confirm 모달 · window.confirm 아님)
    await page.getByTestId('archive-company').click()
    await expect(page.getByTestId('archive-modal')).toBeVisible()
    await page.getByTestId('danger-confirm').click()
    await expect(page).toHaveURL(/\/companies$/)
    await expect(page.getByTestId('toast')).toContainText('휴지통으로 이동')
    await expect(page.getByTestId('toast-action')).toHaveText('되돌리기')
    await expect(page.getByTestId('company-row').filter({ hasText: '삭제테스트상사' })).toHaveCount(0)
    // 휴지통에서 복구
    await page.getByTestId('open-trash').click()
    await expect(page.getByTestId('trash-row').filter({ hasText: '삭제테스트상사' })).toHaveCount(1)
    await page.screenshot({ path: `${SHOTS}/${tag}-h01-trash.png`, fullPage: true })
    await page.getByTestId('trash-row').filter({ hasText: '삭제테스트상사' }).getByTestId('restore').click()
    await expect(page.getByTestId('trash-row').filter({ hasText: '삭제테스트상사' })).toHaveCount(0)
    await page.goto('/companies')
    await expect(page.getByTestId('company-row').filter({ hasText: '삭제테스트상사' })).toHaveCount(1)
    // 목록에서 바로 보관 → 되돌리기 (Undo)
    await page.getByTestId('company-row').filter({ hasText: '삭제테스트상사' }).getByTestId('archive-company').click()
    await expect(page.getByTestId('company-row').filter({ hasText: '삭제테스트상사' })).toHaveCount(0)
    await page.getByTestId('toast-action').click()
    await expect(page.getByTestId('company-row').filter({ hasText: '삭제테스트상사' })).toHaveCount(1)
    // 다시 보관 → 영구삭제: 회사명 불일치면 버튼 비활성, 일치하면 삭제
    await page.getByTestId('company-row').filter({ hasText: '삭제테스트상사' }).getByTestId('archive-company').click()
    await page.goto('/companies/trash')
    await page.getByTestId('trash-row').filter({ hasText: '삭제테스트상사' }).getByTestId('delete-permanent').click()
    await expect(page.getByTestId('delete-modal')).toContainText('미팅 0건')
    await expect(page.getByTestId('delete-modal')).toContainText('되돌릴 수 없습니다')
    await expect(page.getByTestId('danger-confirm')).toBeDisabled()
    await page.getByTestId('danger-typed').fill('다른이름')
    await expect(page.getByTestId('danger-confirm')).toBeDisabled()
    await page.getByTestId('danger-typed').fill('삭제테스트상사')
    await expect(page.getByTestId('danger-confirm')).toBeEnabled()
    await page.screenshot({ path: `${SHOTS}/${tag}-h02-delete-modal.png`, fullPage: true })
    await page.getByTestId('danger-confirm').click()
    await expect(page.getByTestId('trash-row').filter({ hasText: '삭제테스트상사' })).toHaveCount(0)
    await expect(page.getByTestId('toast')).toContainText('영구 삭제')
  })

  test('Handoff guard — 전달된 고객은 영구삭제 차단, 철회하면 운영 OS 이벤트도 보류, 재전달하면 같은 이벤트가 다시 열림', async ({ page }) => {
    await loginPartner(page)
    await prepareCompany(page, '철회테스트')
    await page.getByTestId('start-meeting').click()
    await page.getByTestId('open-quote').click()
    await page.getByTestId('quote-input').fill('대표 말')
    await page.getByRole('button', { name: '저장하고 계속' }).click()
    await answerAll(page)
    await page.getByTestId('end-meeting').click()
    await page.getByTestId('submit-handoff').click()
    await expect(page.getByTestId('handoff-success')).toBeVisible()
    const companyUrl = await page.getByRole('link', { name: /철회테스트 미팅 전략/ }).getAttribute('href')
    // 전달된 고객: 보관은 되지만 영구 삭제는 DB(여기선 local parity)가 거부한다
    await page.goto(companyUrl!)
    await page.getByTestId('archive-company').click()
    await page.getByTestId('danger-confirm').click()
    await page.goto('/companies/trash')
    await expect(page.getByTestId('trash-row').filter({ hasText: '철회테스트' })).toContainText('운영 OS 전달 이력')
    await page.getByTestId('trash-row').filter({ hasText: '철회테스트' }).getByTestId('delete-permanent').click()
    await expect(page.getByTestId('delete-modal')).toContainText('전달된 2차 제안 요청이 있습니다')
    await expect(page.getByTestId('danger-typed')).toHaveCount(0)
    await expect(page.getByTestId('danger-confirm')).toBeDisabled()
    await page.getByRole('button', { name: '닫기' }).click()
    await page.getByTestId('trash-row').filter({ hasText: '철회테스트' }).getByTestId('restore').click()
    // 철회 → Partner withdrawn + 운영 OS 이벤트 ignored(+사유)
    await page.goto(companyUrl!)
    await page.getByTestId('meeting-row').first().getByRole('link').click()
    await expect(page).toHaveURL(/\/handoffs\//)
    await page.getByTestId('withdraw-handoff').click()
    await page.getByTestId('withdraw-reason').fill('대표가 보류 요청')
    await page.getByTestId('danger-confirm').click()
    await expect(page.getByTestId('handoff-withdrawn')).toBeVisible()
    const ev = await page.evaluate(() => JSON.parse(localStorage.getItem('axpartner.customer_events') ?? '[]') as { status?: string; payload: Record<string, unknown> }[])
    expect(ev).toHaveLength(1)
    expect(ev[0].status).toBe('ignored')
    expect(ev[0].payload.withdrawn).toBe(true)
    expect(ev[0].payload.withdraw_reason).toBe('대표가 보류 요청')
    // 전달된 미팅 삭제 시도는 차단되지 않아야 할 이유가 없다 — 철회 후에도 이력이 있으면 삭제 불가
    // 재전달 → 같은 이벤트가 new 로 다시 열리고 새 이벤트를 만들지 않는다
    await page.getByTestId('resubmit-link').click()
    await expect(page.getByTestId('handoff-withdrawn')).toBeVisible()
    await page.getByTestId('submit-handoff').click()
    await expect(page.getByTestId('handoff-success')).toBeVisible()
    const ev2 = await page.evaluate(() => JSON.parse(localStorage.getItem('axpartner.customer_events') ?? '[]') as { status?: string; payload: Record<string, unknown> }[])
    expect(ev2).toHaveLength(1)
    expect(ev2[0].status).toBe('new')
    expect(ev2[0].payload.resubmitted).toBe(true)
    expect(ev2[0].payload.withdrawn).toBeUndefined()
  })

  test('파트너 수정 — 마스터가 이름·직책 변경 → 파트너 인사말·헤더에 반영, 마지막 마스터·본인 강등 차단', async ({ page }) => {
    await loginPartner(page)
    await switchRole(page, '마스터로 전환')
    await page.goto('/master/partners')
    const row = page.getByTestId('member-row').filter({ hasText: '곽주환' })
    await row.getByTestId('edit-member').click()
    await page.getByTestId('member-display-name').fill('곽주환')
    await page.getByTestId('member-title').fill('이사')
    await page.getByTestId('member-save').click()
    await expect(page.getByTestId('member-row').filter({ hasText: '곽주환 이사' })).toHaveCount(1)
    // 마지막 활성 마스터(김상호 = 본인)는 강등·비활성화 불가 — 셀렉트가 잠긴다
    await page.getByTestId('member-row').filter({ hasText: '김상호' }).getByTestId('edit-member').click()
    await expect(page.getByTestId('member-guard')).toBeVisible()
    await expect(page.getByTestId('member-role')).toBeDisabled()
    await expect(page.getByTestId('member-active')).toBeDisabled()
    await page.getByRole('button', { name: '닫기' }).click()
    // 파트너 상세
    await page.getByTestId('member-name').filter({ hasText: '곽주환' }).click()
    await expect(page.getByRole('heading', { name: '곽주환 이사' })).toBeVisible()
    // 파트너로 다시 로그인하면 인사말에 반영된다
    await switchRole(page, '파트너로 전환')
    await page.goto('/')
    await expect(page.getByRole('heading', { name: /안녕하세요, 곽주환 이사님/ })).toBeVisible()
    await expect(page.getByTestId('user-chip-name')).toContainText('곽주환 이사')
    // 원상복구
    await switchRole(page, '마스터로 전환')
    await page.goto('/master/partners')
    await page.getByTestId('member-row').filter({ hasText: '곽주환' }).getByTestId('edit-member').click()
    await page.getByTestId('member-title').fill('팀장')
    await page.getByTestId('member-save').click()
  })

  test('중복 등록 안내 — 같은 회사명이면 먼저 알려 주고, 그래도 등록할 수 있다', async ({ page }) => {
    await loginPartner(page)
    await prepareCompany(page, '중복테스트')
    await page.goto('/companies/new')
    await page.getByTestId('company-name').fill('중복테스트')
    await page.getByTestId('prep-next').click()
    await expect(page.getByTestId('dup-sheet')).toBeVisible()
    await expect(page.getByTestId('open-existing')).toBeVisible()
    await page.getByTestId('register-anyway').click()
    await expect(page.getByTestId('prep-progress')).toHaveText(/2 \/ 4/)
  })

  test('LIVE 오프라인 안전 — 끊긴 채 답해도 기기에 임시 저장, 복구되면 자동 동기화, 새로고침 후 답변 유지', async ({ page, context }) => {
    await loginPartner(page)
    await prepareCompany(page, '오프라인테스트')
    await page.getByTestId('start-meeting').click()
    await expect(page).toHaveURL(/\/live$/)
    await expect(page.getByTestId('save-status')).toHaveAttribute('data-status', 'saved')
    const meetingId = page.url().split('/meetings/')[1].replace('/live', '')
    // local 모드는 localStorage 저장이라 네트워크가 없어도 성공한다 → 저장소의 e2e 훅으로 저장 실패를 흉내 낸다
    await page.evaluate(() => localStorage.setItem('axpartner.test.failSaves', 'true'))
    await context.setOffline(true)
    await page.getByRole('radio').nth(2).click()
    await expect(page.getByTestId('save-status')).toHaveAttribute('data-status', /offline|error/)
    await expect(page.getByTestId('save-status')).toContainText('임시저장됨')
    const draft = await page.evaluate((id) => localStorage.getItem(`axpartner.draft.meeting.${id}`), meetingId)
    expect(draft).toBeTruthy()
    expect(JSON.parse(draft!).synced).toBe(false)
    // 복구 → 자동 재시도 → 저장됨
    await page.evaluate(() => localStorage.removeItem('axpartner.test.failSaves'))
    await context.setOffline(false)
    await expect(page.getByTestId('save-status')).toHaveAttribute('data-status', 'saved', { timeout: 15000 })
    // 새로고침 후 첫 질문 답변이 남아 있다 (두 번째 질문으로 이어진다)
    await page.reload()
    await expect(page.getByTestId('live-progress')).toContainText('2 /')
  })
})
