/**
 * 사례 DB 초기 시드.
 *
 * 원천: 미래AI랩 홈페이지 공개 자료(realProjectsDeep · fundingCases · axIndustryShowcaseV2 · policyAxEvidence2026).
 * "미래AI랩 AX·플랫폼·자금조달 종합리서치" PDF 는 이 저장소에 첨부되지 않아 반영하지 못했다 —
 * Master 가 리서치 자료를 추가하면 AI 추출 → Master 검수 → 승인 → 사례 DB 반영 순서로 들어간다(verification_status).
 *
 * 원칙
 *   - 회사명은 공개 자료 표기(업종·지역)를 그대로 쓴다. 실명·대표자명은 넣지 않는다.
 *   - 실제 공개금액(fundingAmountDisclosed)과 제도상 최대한도(fundingProgramMax)를 반드시 분리한다.
 *   - 민간투자·보증·정책융자·정부 R&D·사업화지원을 혼동하지 않는다.
 *   - 자금 결과는 카드 맨 아래. "이 업체가 받았다고 현재 고객도 받는다는 뜻이 아니다" 를 항상 붙인다.
 */
import type { CaseStudy } from '../types/domain'

const T = '2026-09-22T00:00:00.000Z'

export const CASE_DISCLAIMER =
  '이 업체가 받은 금액이 현재 고객도 같은 금액을 받을 수 있다는 의미는 아닙니다. 승인 여부와 한도는 기업의 재무상태·신용·업력·자금 용도와 신청 시점의 제도에 따라 달라집니다.'

export const CASE_SEED: CaseStudy[] = [
  {
    id: 'case_medwaste',
    companyName: '의료폐기물 수거·운반 기업',
    industry: 'environment',
    subIndustry: '의료폐기물 수거·운반',
    businessModel: 'b2b',
    problem: '병원별 수거 일정·배차·현장 수거량·자재 공급·월정산·미수금이 엑셀과 카톡, 기사 기억에 흩어져 있었다. 병원이 진행상황을 물어보면 사무실이 기사에게 다시 물어봐야 했다.',
    beforeProcess: '기사 카톡 사진 → 사무실 엑셀 정리 → 월말 수기 정산 → 은행 입금 수동 대조',
    axTransition: '현장기사·사무실·대표·병원 관계자 역할을 분리한 Business AX 와 병원용 Customer Platform 을 한 시스템으로 연결했다. 병원이 요청하면 내부에 업무가 생기고, 직원이 처리하면 결과가 병원 화면에 돌아간다.',
    internalAx: '월/주/일 일정·배차·기사 배정, 현장 수거량·자재 공급 동시 입력, 자동 재고차감, 월정산(kg·월정액·박스·혼합형)·청구 스냅샷·입금·미수·통장대사',
    customerPortal: '병원별 격리된 포털 — 수거 요청, 진행상황, 청구·정산 확인',
    aiFunction: '누락·지연·미수 위험 우선순위 표시(고도화 범위)',
    validation: '실제 엑셀 데이터 이관 · 390px 모바일 현장기사 UX · 중복저장·중복차감 방어 검증 (개발·고도화 진행 중)',
    axPath: 'hybrid',
    growthStage: 'growing',
    talkingPoints: [
      '현장 기록 → 정산 → 청구 → 입금 대사가 끊겨 있는 회사라면 구조가 같다.',
      '50~60대 현장 인력도 쓰는 큰 글씨·큰 버튼 화면이 실제로 돌아간다.',
      '고객(병원)이 직접 요청·확인하는 포털이 붙으면 "물어봐야 아는" 전화가 줄어든다.',
    ],
    caveats: [
      '전 항목이 이미 실운영 완료된 상태가 아니라 고도화 범위다 — 그대로 말하지 않는다.',
      '정산 조건이 거래처마다 다른 업종에 적합하다. 단순 소매에는 과한 구조다.',
    ],
    fundingType: 'unknown',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '자금연계 프로젝트(funding: true)로 진행 중이며, 공개된 승인 금액은 없다.',
    year: '2026',
    source: '미래AI랩 홈페이지 · 실제 기업 AX 프로젝트(realProjectsDeep: medwaste)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['수거', '배차', '정산', '미수금', '고객포털', '현장기사'],
    problemAreas: ['info_scatter', 'quote_order', 'ceo_dependency', 'customer_mgmt'],
    updatedAt: T,
  },
  {
    id: 'case_wellness',
    companyName: 'Wellness Care 기업',
    industry: 'medical',
    subIndustry: '웰니스 케어',
    businessModel: 'b2c',
    problem: '회원 방문·재방문·상담 기록이 담당자 기억과 메신저에 남아, 이탈 위험 회원을 늦게 알았다.',
    beforeProcess: '수기 예약 → 방문 후 개인 메모 → 재방문 연락은 담당자 기억',
    axTransition: 'Wellness Business AX 와 회원용 MY WELLNESS 포털을 함께 설계했다. 방문·상담 기록이 쌓이고 재방문 시점이 먼저 보인다.',
    internalAx: '회원·방문·상담 기록, 재방문 알림, 직원 역할별 화면',
    customerPortal: 'MY WELLNESS — 회원이 예약·기록·안내를 직접 확인',
    aiFunction: '이탈 위험·재방문 우선순위 제안',
    validation: 'Pilot 준비 단계. RLS 실계정 A/B 격리검증은 검증 대기.',
    axPath: 'hybrid',
    growthStage: 'early',
    talkingPoints: ['재방문 관리가 매출의 본체인 B2C 서비스에 그대로 적용된다.', '고객 포털이 있으면 "예약 확인 전화" 가 사라진다.'],
    caveats: ['Pilot 준비 단계라 실운영 성과 수치는 없다.'],
    fundingType: 'unknown',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '자금연계 프로젝트로 진행 중. 공개된 승인 금액 없음.',
    year: '2026',
    source: '미래AI랩 홈페이지 · 실제 기업 AX 프로젝트(realProjectsDeep: wellness)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['재방문', '회원관리', '예약', '포털'],
    problemAreas: ['customer_mgmt', 'repurchase', 'data_potential'],
    updatedAt: T,
  },
  {
    id: 'case_leather',
    companyName: '피혁 제조·도소매 기업',
    industry: 'manufacturing',
    subIndustry: '피혁 제조·도소매',
    businessModel: 'b2b',
    problem: '제품·재고·견적·재구매·거래처 영업기회가 각각 따로 관리돼 거래처가 먼저 연락해야 다음 주문이 시작됐다.',
    beforeProcess: '전화·카톡 주문 → 엑셀 재고 → 수기 견적 → 재주문은 거래처 연락 대기',
    axTransition: '제품·재고·견적·재구매·거래처 영업기회를 연결한 B2B AX 로 바꿨다.',
    internalAx: '제품·재고·견적·거래처 통합, 재구매 시점 표시',
    customerPortal: '거래처 주문·견적 확인(범위 내)',
    aiFunction: '재구매 시점·영업 Action 제안',
    validation: 'MVP 고도화 진행',
    axPath: 'internal_ax',
    growthStage: 'stable',
    talkingPoints: ['견적·재고·재구매가 따로 노는 제조·도소매 회사의 표준 구조다.', '"거래처가 먼저 연락해야 주문이 시작된다" 는 회사에 바로 설명된다.'],
    caveats: ['자금조달 결과는 공개돼 있지 않다.'],
    fundingType: 'unknown',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '',
    year: '2026',
    source: '미래AI랩 홈페이지 · 실제 기업 AX 프로젝트(realProjectsDeep: leather)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['견적', '재고', '재구매', '거래처'],
    problemAreas: ['quote_order', 'repurchase', 'info_scatter', 'customer_mgmt'],
    updatedAt: T,
  },
  {
    id: 'case_metrology',
    companyName: '산업계측·장비유통 기업',
    industry: 'distribution',
    subIndustry: '산업계측·장비 유통',
    businessModel: 'b2b',
    problem: '재고·수요·견적·재구매가 담당자별로 관리돼 영업 Action 이 사람 기억에 의존했다.',
    beforeProcess: '엑셀 재고 + 개인 견적 파일 + 카톡 문의',
    axTransition: '재고·수요·견적·재구매와 영업 Action 을 연결한 Business AX.',
    internalAx: '재고·수요·견적·재구매 통합 화면, 오늘 연락할 거래처',
    customerPortal: '',
    aiFunction: '재구매·영업 Action 우선순위',
    validation: 'Business AX MVP 진행',
    axPath: 'internal_ax',
    growthStage: 'stable',
    talkingPoints: ['유통·장비 B2B 에서 "누구에게 왜 지금 연락할지" 를 시스템이 알려주는 구조.'],
    caveats: ['고객포털 없이 내부 AX 만으로 시작한 사례 — 접점 구조가 필요한 회사와는 다르다.'],
    fundingType: 'unknown',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '',
    year: '2026',
    source: '미래AI랩 홈페이지 · 실제 기업 AX 프로젝트(realProjectsDeep: metrology)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['재고', '견적', '재구매', '영업'],
    problemAreas: ['repurchase', 'quote_order', 'customer_mgmt', 'data_potential'],
    updatedAt: T,
  },
  {
    id: 'case_elec',
    companyName: '전기·정보통신·프로젝트관리 기업',
    industry: 'construction',
    subIndustry: '전기·정보통신 시공',
    businessModel: 'both',
    problem: '현장·프로젝트·견적·원가·수금이 따로 관리돼 추가작업이 청구로 이어지지 않았다.',
    beforeProcess: '현장 카톡 사진 → 주간 수기 보고서 → 구두 추가작업 → 정산 때 누락',
    axTransition: '현장·프로젝트·견적·원가·수금과 고객 서비스 흐름을 연결한 Hybrid AX.',
    internalAx: '프로젝트·현장·견적·원가·수금 통합',
    customerPortal: '발주처가 진행상황·증빙을 직접 확인',
    aiFunction: '지연·추가비용 시작 지점 감지(범위)',
    validation: 'Hybrid AX MVP 진행',
    axPath: 'hybrid',
    growthStage: 'growing',
    talkingPoints: ['건설·시공에서 "무료로 끝나던 추가작업" 을 근거 있는 청구로 바꾸는 구조.', '발주처가 물어보기 전에 진행보고가 먼저 보인다.'],
    caveats: ['프로젝트형 사업에 맞다. 반복 생산형 제조와는 구조가 다르다.'],
    fundingType: 'unknown',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '',
    year: '2026',
    source: '미래AI랩 홈페이지 · 실제 기업 AX 프로젝트(realProjectsDeep: elec)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['현장', '프로젝트', '견적', '원가', '수금'],
    problemAreas: ['info_scatter', 'quote_order', 'ceo_dependency'],
    updatedAt: T,
  },
  {
    id: 'case_pump',
    companyName: '산업용 설비·펌프 기업',
    industry: 'manufacturing',
    subIndustry: '산업용 설비·펌프 · AS',
    businessModel: 'b2b',
    problem: '설비 설치·AS·재고·발주·정산 기록이 흩어져 AS 이력과 재고가 사람 기억에 의존했다.',
    beforeProcess: '전화 AS 접수 → 수기 이력 → 엑셀 재고 → 월말 정산',
    axTransition: '설비·AS·설치·재고·발주·정산을 연결한 운영 AX.',
    internalAx: '설비 이력·AS·재고·발주·정산 통합',
    customerPortal: '',
    aiFunction: 'AS 주기·재고 발주 시점 제안',
    validation: 'Business AX MVP 진행',
    axPath: 'internal_ax',
    growthStage: 'stable',
    talkingPoints: ['설치·AS 가 반복되는 설비 회사의 표준 구조.'],
    caveats: [],
    fundingType: 'unknown',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '',
    year: '2026',
    source: '미래AI랩 홈페이지 · 실제 기업 AX 프로젝트(realProjectsDeep: pump)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['설비', 'AS', '재고', '발주'],
    problemAreas: ['info_scatter', 'repetitive_work', 'quote_order'],
    updatedAt: T,
  },
  /* ── 자금조달 사례(홈페이지 공개) — AX 프로젝트가 아니라 정책자금·보증 컨설팅 결과. 자금 유형 구분용 ── */
  {
    id: 'fund_construction_special',
    companyName: '건설·특수시공 기업 (서울 양천구)',
    industry: 'construction',
    subIndustry: '특수필터 제조·시공',
    businessModel: 'b2b',
    problem: '법인 인수 직후 전 대표의 부채 등 복합 재무 이슈로 추가 조달이 막혀 있었다.',
    beforeProcess: '은행 대출 반복 거절',
    axTransition: '(AX 프로젝트 아님) 재무를 먼저 정리하고 특수필터 제조 기술성과 상환 능력을 중심으로 기관을 나눠 준비했다.',
    internalAx: '',
    customerPortal: '',
    aiFunction: '',
    validation: '',
    axPath: 'simple_automation',
    growthStage: 'growing',
    talkingPoints: ['기술성과 상환 능력을 자료로 재구성하면 재무 이슈가 있어도 길이 열릴 수 있다는 사례.'],
    caveats: ['AX 구축 사례가 아니다. 자금 유형(보증 + 소진공)과 금액 구분을 정확히 말한다.', '이 금액은 이 회사의 재무·기술성에 대한 결과다.'],
    fundingType: 'guarantee',
    fundingAmountDisclosed: 300_000_000,
    fundingProgramMax: null,
    fundingNote: '신용보증기금 2억 + 소상공인진흥공단 3천 + 혁신성장 (합계 3억 원, 공개 표기 기준)',
    year: '2025',
    source: '미래AI랩 홈페이지 · 정책자금 실제 사례(fundingCases)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['보증', '신보', '소진공', '재무정리'],
    problemAreas: ['funding_interest'],
    updatedAt: T,
  },
  {
    id: 'fund_coffee',
    companyName: '커피 로스터리 (경기 광주)',
    industry: 'food',
    subIndustry: '커피 로스팅',
    businessModel: 'both',
    problem: '연매출 약 4,000만 원 규모에 기존 대출이 있어 매출 기준으로는 조달이 어려웠다.',
    beforeProcess: '',
    axTransition: '(AX 프로젝트 아님) 매출 대신 로스팅 기술성을 중심으로 기술보증기금 방향으로 준비, 약 5주 만에 승인.',
    internalAx: '',
    customerPortal: '',
    aiFunction: '',
    validation: '',
    axPath: 'simple_automation',
    growthStage: 'early',
    talkingPoints: ['매출이 작아도 기술성이 뚜렷하면 기보 방향이 열릴 수 있다는 사례.'],
    caveats: ['AX 구축 사례가 아니다.', '기록상 금리 연 4%대 — 시점·제도에 따라 달라진다.'],
    fundingType: 'guarantee',
    fundingAmountDisclosed: 100_000_000,
    fundingProgramMax: null,
    fundingNote: '기술보증기금 승인 1억 원 (진행 약 5주)',
    year: '2025',
    source: '미래AI랩 홈페이지 · 정책자금 실제 사례(fundingCases)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['기보', '기술성', '초기기업'],
    problemAreas: ['funding_interest'],
    updatedAt: T,
  },
  {
    id: 'fund_franchise_tableorder',
    companyName: '외식 프랜차이즈 (서울 강남구)',
    industry: 'food',
    subIndustry: '외식 프랜차이즈',
    businessModel: 'b2c',
    problem: '기존 대출 다수로 추가 대출이 계속 거절됐다.',
    beforeProcess: '',
    axTransition: '(AX 프로젝트 아님) 2년 이상 축적된 테이블오더 운영 실적을 혁신성 관점으로 재정리해 소상공인 혁신성장촉진자금으로 진행.',
    internalAx: '',
    customerPortal: '',
    aiFunction: '',
    validation: '',
    axPath: 'simple_automation',
    growthStage: 'stable',
    talkingPoints: ['"실제로 돌아가는 시스템 + 쌓인 운영 데이터" 가 혁신성 설명 근거가 된 사례 — AX 의 자금 설명력 논리와 같은 구조.'],
    caveats: ['테이블오더는 기성 솔루션이었다. 자체 AX 구축 사례가 아니다.', '기록상 금리 연 2.99% — 시점·제도에 따라 다르다.'],
    fundingType: 'policy_loan',
    fundingAmountDisclosed: 60_000_000,
    fundingProgramMax: null,
    fundingNote: '소상공인 혁신성장촉진자금 6,000만 원 (진행 약 6주)',
    year: '2025',
    source: '미래AI랩 홈페이지 · 정책자금 실제 사례(fundingCases)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['혁신성장', '운영데이터', '테이블오더'],
    problemAreas: ['funding_interest', 'data_potential'],
    updatedAt: T,
  },
  {
    id: 'fund_dryice',
    companyName: '드라이아이스 도소매·임가공 (경기 광주)',
    industry: 'distribution',
    subIndustry: '도소매·임가공',
    businessModel: 'b2b',
    problem: '보증부 자금 조달과 고용 구조 정비가 동시에 필요했다.',
    beforeProcess: '',
    axTransition: '(AX 프로젝트 아님) 자금 방향을 먼저 잡고 고용지원금을 함께 활용할 수 있게 구조를 정리.',
    internalAx: '',
    customerPortal: '',
    aiFunction: '',
    validation: '',
    axPath: 'simple_automation',
    growthStage: 'stable',
    talkingPoints: ['자금과 고용지원금은 다른 제도다 — 구분해서 설명하는 예시로 쓴다.'],
    caveats: ['보증부 자금(7,000만)과 고용지원금 구조 정비는 별개 결과다. 합쳐서 말하지 않는다.'],
    fundingType: 'guarantee',
    fundingAmountDisclosed: 70_000_000,
    fundingProgramMax: null,
    fundingNote: '보증부 자금 7,000만 원 + 고용지원금 구조 정비(금액 비공개)',
    year: '2025',
    source: '미래AI랩 홈페이지 · 정책자금 실제 사례(fundingCases)',
    sourceDate: '2026-09',
    verificationStatus: 'verified',
    keywords: ['보증', '고용지원금'],
    problemAreas: ['funding_interest', 'hiring_burden'],
    updatedAt: T,
  },
  /* ── 업종별 AX 활용 예시(홈페이지 공개 시나리오) — 실제 기업이 아닌 업종 패턴. needs_review 로 둔다 ── */
  {
    id: 'pattern_food_prep',
    companyName: '외식·프랜차이즈 업종 패턴',
    industry: 'food',
    subIndustry: '외식·배달',
    businessModel: 'b2c',
    problem: '점주 경험으로 준비량을 결정하고, 단체문의는 전화·메신저로 받아 견적과 일정이 흩어진다.',
    beforeProcess: 'POS(얼마 팔았는지) + 점주 감(준비량) + 카톡 단체문의',
    axTransition: '준비량·폐기 위험 메뉴가 먼저 보이고, 단체문의가 견적·일정으로 자동 연결되는 구조.',
    internalAx: '준비량·폐기·리뷰 문제 화면, 단체주문 접수·견적',
    customerPortal: '단체·기업 주문 접수',
    aiFunction: '내일 준비량·폐기 위험 제안',
    validation: '업종 시나리오(실제 프로젝트 아님)',
    axPath: 'hybrid',
    growthStage: 'growing',
    talkingPoints: ['POS 는 얼마 팔았는지, AX 는 무엇을 팔아 실제로 얼마가 남았는지를 보여준다.'],
    caveats: ['실제 기업 사례가 아니라 업종 패턴이다. "비슷한 회사가 이렇게 했다" 로 말하지 않는다.'],
    fundingType: 'none',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '',
    year: '2026',
    source: '미래AI랩 홈페이지 · 업종별 AX(axIndustryShowcaseV2: food-franchise)',
    sourceDate: '2026-09',
    verificationStatus: 'needs_review',
    keywords: ['준비량', '폐기', '단체주문'],
    problemAreas: ['data_potential', 'quote_order', 'customer_mgmt'],
    updatedAt: T,
  },
  {
    id: 'pattern_service_crm',
    companyName: '상담·예약형 서비스 업종 패턴',
    industry: 'service',
    subIndustry: '상담·예약·계약형 서비스',
    businessModel: 'b2c',
    problem: '예약이 취소되면 그 시간이 비고, 견적을 보낸 뒤 담당자가 기억날 때 연락한다. 담당자가 바뀌면 고객이 같은 설명을 다시 한다.',
    beforeProcess: '수기 예약 + 카톡 상담 + 개인 기억 후속',
    axTransition: '오늘 다시 연락할 고객과 놓치면 안 되는 예약·계약이 먼저 보이는 구조.',
    internalAx: '상담·견적·예약·후속연락 통합',
    customerPortal: '예약·상담 확인',
    aiFunction: '누구에게 왜 지금 연락할지 제안',
    validation: '업종 시나리오(실제 프로젝트 아님)',
    axPath: 'hybrid',
    growthStage: 'growing',
    talkingPoints: ['취소된 예약과 떠난 고객을 대기고객·재예약·재구매로 연결하는 구조.'],
    caveats: ['업종 패턴이다. 실제 기업 사례처럼 말하지 않는다.'],
    fundingType: 'none',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '',
    year: '2026',
    source: '미래AI랩 홈페이지 · 업종별 AX(axIndustryShowcaseV2: sales-crm)',
    sourceDate: '2026-09',
    verificationStatus: 'needs_review',
    keywords: ['예약', '상담', '후속연락', '재구매'],
    problemAreas: ['customer_mgmt', 'repurchase', 'info_scatter'],
    updatedAt: T,
  },
  {
    id: 'pattern_logistics',
    companyName: '도매·물류 업종 패턴',
    industry: 'logistics',
    subIndustry: '도매·배송',
    businessModel: 'b2b',
    problem: '거래처가 전화와 메신저로 주문하고, 재고는 창고에 오래 쌓인 뒤에야 담당자가 수기로 할인을 결정한다.',
    beforeProcess: '전화·메신저 주문 + 엑셀 재고 + 수기 발주',
    axTransition: '오늘 발주할 상품·정리할 재고·먼저 확인할 배송문제가 바로 보이고, 재구매 시점에 함께 제안할 상품이 뜨는 구조.',
    internalAx: '주문·재고·발주·배송 통합',
    customerPortal: '거래처 주문 포털',
    aiFunction: '재구매 시점·발주 제안',
    validation: '업종 시나리오(실제 프로젝트 아님)',
    axPath: 'hybrid',
    growthStage: 'growing',
    talkingPoints: ['전화·메신저 주문 → 주문포털 + 주문 DB + 알림 의 표준 구조.'],
    caveats: ['업종 패턴이다.'],
    fundingType: 'none',
    fundingAmountDisclosed: null,
    fundingProgramMax: null,
    fundingNote: '',
    year: '2026',
    source: '미래AI랩 홈페이지 · 업종별 AX(axIndustryShowcaseV2: wholesale-logistics)',
    sourceDate: '2026-09',
    verificationStatus: 'needs_review',
    keywords: ['주문', '재고', '발주', '배송'],
    problemAreas: ['quote_order', 'info_scatter', 'repurchase'],
    updatedAt: T,
  },
]
